foreach(PROCESSOR x86_64 AMD64 i686 aarch64 arm64 riscv64)
  unset(DS_ARCH CACHE)
  set(CMAKE_SYSTEM_PROCESSOR "${PROCESSOR}")
  include("${DS_SOURCE_DIR}/cmake/Architecture.cmake")
  if (PROCESSOR MATCHES "^(x86_64|AMD64|i686)$")
    set(EXPECTED AVX)
  else()
    set(EXPECTED OFF)
  endif()
  if (NOT DS_ARCH STREQUAL EXPECTED)
    message(FATAL_ERROR "Wrong ISA default for ${PROCESSOR}: ${DS_ARCH}")
  endif()
endforeach()
