#ifndef DEVILS_ENGINE_SCRIPT_NUMERIC_COMMANDS_MACRO_H
#define DEVILS_ENGINE_SCRIPT_NUMERIC_COMMANDS_MACRO_H

#define NUMERIC_COMMANDS_LIST2 \
  NUMERIC_COMMAND_BLOCK_FUNC(add) \
  NUMERIC_COMMAND_BLOCK_FUNC(multiply) \
  NUMERIC_COMMAND_BLOCK_FUNC(sub) \
  NUMERIC_COMMAND_BLOCK_FUNC(divide) \
  NUMERIC_COMMAND_BLOCK_FUNC(mod) \
  NUMERIC_COMMAND_BLOCK_FUNC(min) \
  NUMERIC_COMMAND_BLOCK_FUNC(max) \
  NUMERIC_COMMAND_BLOCK_FUNC(add_sequence) \
  NUMERIC_COMMAND_BLOCK_FUNC(multiply_sequence) \
  NUMERIC_COMMAND_BLOCK_FUNC(min_sequence) \
  NUMERIC_COMMAND_BLOCK_FUNC(max_sequence) \
  
#endif
