# Keep the existing x86 baseline; other targets default to portable code.
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" DS_PROCESSOR)
set(DS_DEFAULT_ARCH OFF)
if (DS_PROCESSOR MATCHES "^(x86_64|amd64|i[3-6]86|x86)$")
  set(DS_DEFAULT_ARCH AVX)
endif()
set(DS_ARCH "${DS_DEFAULT_ARCH}" CACHE STRING "ISA baseline: OFF, AVX, AVX2, NATIVE")
set_property(CACHE DS_ARCH PROPERTY STRINGS OFF AVX AVX2 NATIVE)
if (NOT DS_ARCH MATCHES "^(OFF|AVX|AVX2|NATIVE)$")
  message(FATAL_ERROR "Unknown DS_ARCH: ${DS_ARCH}")
endif()
if (DS_ARCH MATCHES "^(AVX|AVX2)$" AND NOT DS_DEFAULT_ARCH STREQUAL "AVX")
  message(FATAL_ERROR "DS_ARCH=${DS_ARCH} requires an x86 target; use OFF for ${CMAKE_SYSTEM_PROCESSOR}")
endif()
